# Site settings
title: Mariel de Jesus™
description: >-
  Apenas um cara comum que gosta de tecnologia e de inventar coisas. Pai de duas filhas muito lindas e marido de uma mulher maravilhosa.
lang: pt-BR
timezone: America/Belem
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: 
mode: dark # default theme "dark" | "light"


# Profile settings
author:
  name: Mariel de Jesus™
  bio: >-
    Apenas um <a href="https://www.instagram.com/marieldejesus12/" target="_blank" rel="noopener">cara comum</a> que gosta de tecnologia e de inventar coisas. Pai de <a href="https://www.facebook.com/photo?fbid=2993608304024304&set=a.313803925338102" target="_blank" rel="noopener">duas filhas</a> muito lindas e marido de uma <a href="https://www.instagram.com/ildenerramos12/" target="_blank" rel="noopener">mulher maravilhosa</a>.
  username: marieldejesus12
  email: marieldejesus12@gmail.com
  avatar: /assets/img/avatar.jpg

# Url settings
url: "https://marieldejesus12.gitlab.io"
baseurl:
permalink: /:title/
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: true

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Follow Buttons
facebook_url: https://www.facebook.com/marieldejesus12/
twitter_url: https://twitter.com/marieldejesus12
linkedin_url: https://www.linkedin.com/in/marieldejesus12
googleplus_url:
pinterest_url:
instagram_url: https://www.instagram.com/marieldejesus12
gitlab_url: https://gitlab.com/marieldejesus12
telegram_url: https://t.me/marieldejesus12
youtube_url: https://www.youtube.com/marieldejesus12
gmail_url: mailto:marieldejesus12@gmail.com

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - .github

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
  - jekyll-compose
  - rouge
  - jekyll-seo-tag
